export const MODULE_NAME = 'SESSION';

export const ACTION_TYPES = {
  INITIALIZE: 'INITIALIZE',
  AUTHENTICATED: 'AUTHENTICATED',
  RESTORED: 'RESTORED',
  LOGOUT: 'LOGOUT',
  DESTROY: 'DESTROY',
};
