export const MODULE_NAME = 'REMINDER';

export const ACTION_TYPES = {
  FETCH_MANY: 'FETCH_MANY',
  SAVE_MANY: 'SAVE_MANY',
  FETCH_ONE: 'FETCH_ONE',
  SAVE_ONE: 'SAVE_ONE',
  FETCH_FAILED: 'FETCH_FAILED',
};
