/**
 * Reminder API
 * Reminder API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The root of the ErrorObject type\'s schema.
 */
export interface ErrorObject { 
    /**
     * Unique identifier for this incident
     */
    id?: string;
    /**
     * The application error code
     */
    code: string;
    /**
     * Error message
     */
    message?: string;
}

