/**
 * Reminder API
 * Reminder API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The root of the Reminder type\'s schema
 */
export interface Reminder { 
    /**
     * unique id of the reminder
     */
    id: number;
    /**
     * Date reminder was added
     */
    createdDate?: string;
    /**
     * Date reminder was modified
     */
    modifiedDate?: string;
    title?: string;
    body?: string;
}

