/**
 * Reminder API
 * Reminder API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The root of the User type\'s schema
 */
export interface User { 
    /**
     * unique id of the user
     */
    id: number;
    username?: string;
    password?: string;
    firstName?: string;
    lastName?: string;
}

